import { expect, test } from '@playwright/test';
import { prepareAppPage, readDocument, register, resetTestData, seedWord } from './helpers.js';

test.beforeEach(async ({ request }) => resetTestData(request));

test('C04 W16: date JSON review returns, abandons and confirms only scoped edits; deletion stays scoped', async ({ page, request }) => {
  const assertNoProductionRequests = await prepareAppPage(page);
  await register(page, 'date-word-json@example.test');
  await seedWord(page, request, 'day-a', '어제', '昨天', { date: '2026-09-15' });
  await seedWord(page, request, 'day-b', '오늘', '今天', { date: '2026-09-21' });
  await page.getByRole('button', { name: '日曆' }).click();
  await page.locator('.calendar-grid button.day:not(.muted)').nth(14).click();
  await page.getByRole('button', { name: '查看日期' }).click();
  await expect(page.getByRole('heading', { name: '日期筆記' })).toBeVisible();
  await expect(page.locator('.word-grid .word-card')).toHaveCount(1);
  const actions = page.locator('.notebook-actions');
  await actions.locator('.action-menu summary').click();
  await actions.getByRole('button', { name: '匯出 JSON' }).click();
  const exported = JSON.parse(await page.getByRole('dialog').locator('.json-code').textContent());
  expect(exported.data.map((item) => item.ko)).toEqual(['어제']);
  await page.getByRole('dialog').getByRole('button', { name: '關閉' }).click();
  await actions.getByRole('button', { name: '新增', exact: true }).click();
  let addDialog = page.getByRole('dialog');
  await expect(addDialog.getByLabel('日期')).toBeDisabled();
  await addDialog.getByLabel('韓文 *').fill('그제');
  await addDialog.getByLabel('詞性 / 類型 *').selectOption('名詞');
  await addDialog.locator('.meaning-editor-card').getByLabel('中文 *').fill('前天');
  await addDialog.getByRole('button', { name: '新增到單字庫' }).click();
  await expect(addDialog).toHaveCount(0);
  await expect(page.locator('.word-grid .word-card')).toHaveCount(2);
  await actions.locator('.action-menu summary').click();
  await actions.getByRole('button', { name: '修改 JSON' }).click();
  let dialog = page.getByRole('dialog');
  const editor = dialog.locator('.json-editor');
  const original = JSON.parse(await editor.inputValue());
  expect(original.data).toHaveLength(2);
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
  await dialog.getByRole('button', { name: '複製' }).click();
  expect(JSON.parse(await page.evaluate(() => navigator.clipboard.readText()))).toEqual(original);
  await editor.fill('{ broken');
  await dialog.getByRole('button', { name: '檢查變更' }).click();
  await expect(dialog.locator('.json-edit-error')).toBeVisible();
  expect((await readDocument(page, request, 'records', 'day-a')).fields.item.mapValue.fields.meanings.arrayValue.values[0].mapValue.fields.zh.stringValue).toBe('昨天');
  original.data[0].meanings[0].zh = '昨日';
  await editor.fill(JSON.stringify(original));
  await dialog.getByRole('button', { name: '檢查變更' }).click();
  await expect(dialog.getByText('即將修改 1 張單字卡')).toBeVisible();
  await dialog.getByRole('button', { name: '返回編輯' }).click();
  await expect(dialog.getByText('即將修改 1 張單字卡')).toHaveCount(0);
  await dialog.getByRole('button', { name: '檢查變更' }).click();
  await dialog.getByRole('button', { name: '放棄' }).click();
  expect((await readDocument(page, request, 'records', 'day-a')).fields.item.mapValue.fields.meanings.arrayValue.values[0].mapValue.fields.zh.stringValue).toBe('昨天');
  await actions.locator('.action-menu summary').click();
  await actions.getByRole('button', { name: '修改 JSON' }).click();
  dialog = page.getByRole('dialog');
  await dialog.locator('.json-editor').fill(JSON.stringify(original));
  await dialog.getByRole('button', { name: '檢查變更' }).click();
  await dialog.getByRole('button', { name: '確認送出' }).click();
  await expect(dialog).toHaveCount(0);
  await expect.poll(async () => (await readDocument(page, request, 'records', 'day-a'))?.fields.item.mapValue.fields.meanings.arrayValue.values[0].mapValue.fields.zh.stringValue).toBe('昨日');
  expect((await readDocument(page, request, 'records', 'day-b')).fields.item.mapValue.fields.meanings.arrayValue.values[0].mapValue.fields.zh.stringValue).toBe('今天');
  await actions.locator('.action-menu summary').click();
  page.once('dialog', (confirm) => confirm.dismiss());
  await actions.getByRole('button', { name: '刪除本日單字' }).click();
  expect((await readDocument(page, request, 'records', 'day-a')).fields.deletedAt).toBeUndefined();
  await actions.locator('.action-menu summary').click();
  page.once('dialog', (confirm) => confirm.accept());
  await actions.getByRole('button', { name: '刪除本日單字' }).click();
  await expect.poll(async () => (await readDocument(page, request, 'records', 'day-a'))?.fields.deletedAt?.timestampValue).toBeTruthy();
  expect((await readDocument(page, request, 'records', 'day-b')).fields.deletedAt).toBeUndefined();
  assertNoProductionRequests();
});
